name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: github.event.repository.name != 'template-php-package'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        dependencies: [lowest, stable]
    name: PHP ${{ matrix.php }} / ${{ matrix.dependencies }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: ramsey/composer-install@v4
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - run: composer test
